### PR TITLE
Links fixes in docs

### PR DESCRIPTION
**Pull request by rowanjacobs**
Just fixing a couple links in the readme.

### CODE REVIEW

**Comment by bkrannich** [comment]
@rowanjacobs - see #12 for the first fix. I guess the ask to rebase your commit on the develop branch that I received will also come to you.

**Comment by rowanjacobs** [comment]
Rebased on develop!

**Comment by suhlig** [comment]
Thanks, @rowanjacobs. Something got borked - your PR now contains 161 changes. Could you perhaps start from scratch? Alternatively, would you be OK with us just cherry-picking fc32824?

**Comment by rowanjacobs** [comment]
Oops, I have no idea how my rebase got that gnarly. Go ahead and cherry pick the one commit!

**Comment by rowanjacobs** [comment]
closing, see #22

**Pull request closed without merging**
