### PR TITLE
Fix custom key spelling for LoggregatorCertPath

### PR DESCRIPTION
**Pull request by Birdrock**
Thanks for contributing to Eirini! In order for your pull request to be accepted, we would like to ask you the following:

1. Please base your PR off the `master` branch.
Forked on master.

1. Describe the change on a conceptual level. How does it work, and why should it exist? Ideally, you contribute a few words to the README, too.
Unfortunately, it looks like a typo made it into the custom key for yaml unmarshalling for `MetricsCollectorConfig`. The key is inconsistent with other loggregator keys.

1. Please provide automated tests (preferred) or instructions for manually testing your change.
Test coverage does not currently extend to unmarshalling out of json; test fixtures provide data directly. I can add test coverage if it is desired.

### CODE REVIEW

**Comment by Birdrock** [comment]
This is most definitely a breaking change since it is a change to the custom key used to unmarshal.

**Comment by jimmykarily** [comment]
We should also change this: https://github.com/cloudfoundry-incubator/eirini-release/blob/master/helm/eirini/templates/configmap.yaml#L71

**Comment by Birdrock** [comment]
@jimmykarily Would you like me to make a PR against the eirini-release repository, and reference it here?

**Comment by jimmykarily** [comment]
My comment was just a note so we don't forget but sure, that would be great.

**Comment by Birdrock** [comment]
Corresponding [PR for eirini-release](https://github.com/cloudfoundry-incubator/eirini-release/pull/171)

**Comment by georgethebeatle** [comment]
Thanks for contriobuting @Birdrock

**Pull request merged**
