### PR TITLE
Parameterize the base image for the staging image

### PR DESCRIPTION
**Pull request by jimmykarily**
by extracting bash functions in a sourceable file and using a build arg for the base image.

Also remove unused `stack` ARG from Dockerfile.

### CODE REVIEW

**Comment by jimmykarily** [comment]
This change allows us to build a staging image based on a different stack.

**Comment by nimakaviani** [comment]
@jimmykarily the staging process is updated/changed significantly and now lives in a separate repo here: https://github.com/cloudfoundry-incubator/eirini-staging/

Also, we are no longer building the binaries for `builder` and `launcher` in eirini and strictly rely on the binaries shipped in `packs/cf`. The longer term plan is to have the code for builder and launcher included in staging and remove the dependency to `packs/cf`.

In the interim, if you want to change the staging stack, you will need to do a deeper surgical change here: https://github.com/eirini-forks/packs and then create your staging images here:  https://github.com/cloudfoundry-incubator/eirini-staging/blob/master/scripts/image.sh

**Comment by thardeck** [comment]
@nimakaviani Thanks for the explanation. Is the old image still being used or was this change already released?

**Comment by nimakaviani** [comment]
@thardeck the change has not been released yet but we are pulling it into our develop branch. You can track the changes I discussed above in PR https://github.com/cloudfoundry-incubator/eirini/pull/50

The old image is still used in the latest release of eirini if you use native staging.

**Comment by jimmykarily** [comment]
ok we will look into the new repo first and come back with whatever changes are needed. Thanks. Closing this one.

**Pull request closed without merging**
